University Management System/Models/CourseAssignToTeacher.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace University_Management_System.Models
{
    public class CourseAssignToTeacher
    {

        public int Id { get; set; }

        [Required]
        public int DepartmentId { get; set; }
        public virtual Department Department { get; set; }

        [Required]
        public int TeacherId { get; set; }
        public virtual Teacher Teacher { get; set; }

        [Display(Name = "Credit to be Taken")]
        [Editable(false)]
        [DefaultValue(0.0)]
        public double CreditTaken { get; set; }

        [Display(Name = "Remaining Credit")]
        [Editable(false)]
        [DefaultValue(0.0)]
        public double CreditLeft { get; set; }

        [Required]
        public int CourseID { get; set; }
        public virtual Course Course { get; set; }


        public string Name { get; set; }
         
        public double Credit { get; set; }


    }
}

University Management System/Controllers/CourseAssignToTeacherController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using University_Management_System.Models;


namespace University_Management_System.Controllers
{
    public class CourseAssignToTeacherController : Controller
    {
        private StudentDBContext db = new StudentDBContext();

        // GET: /CourseAssign/
        public ActionResult Index()
        {
            var courseassigns = db.CourseAssignToTeachers.Include(c => c.Course).Include(c => c.Department).Include(c => c.Teacher);
            return View(courseassigns.ToList());
        }

        public ActionResult ViewCourseStatistics()
        {
            ViewBag.Departments = db.Deparments.ToList();
            return View();
        }

        public JsonResult ShowCourseStatistics(int deptId)
        {
            var courses = db.Courses.Where(m => m.DepartmentId == deptId).ToList();
            return Json(courses, JsonRequestBehavior.AllowGet);
        }


        // GET: /CourseAssign/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseAssignToTeacher courseassign = db.CourseAssignToTeachers.Find(id);
            if (courseassign == null)
            {
                return HttpNotFound();
            }
            return View(courseassign);
        }

        // GET: /CourseAssign/Create
        public ActionResult Save()
        {
            //ViewBag.CourseID = new SelectList(db.Courses, "Id", "CourseCode");
            //ViewBag.DepartmentId = new SelectList(db.Departments, "Id", "DeptCode");
            //ViewBag.TeacherId = new SelectList(db.Teachers, "Id", "Name");

            ViewBag.Departments = db.Deparments.ToList();

            return View();
        }

        public JsonResult GetTeacherByDeptId(int deptId)
        {
            var teachers = db.Teachers.Where(m => m.DepartmentId == deptId).ToList();
            return Json(teachers, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCourseByDeptId(int deptId)
        {
            var courses = db.Courses.Where(m => m.DepartmentId == deptId).ToList();
            return Json(courses, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTeacherById(int TeacherId)
        {
            var teacher = db.Teachers.FirstOrDefault(m => m.Id == TeacherId);
            return Json(teacher, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCourseById(int courseId)
        {
            Course aCourse = db.Courses.FirstOrDefault(m => m.Id == courseId);
            return Json(aCourse, JsonRequestBehavior.AllowGet);
        }

        // POST: /CourseAssign/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save([Bind(Include = "Id,DepartmentId,TeacherId,CreditTaken,CourseID,Name,Credit")] CourseAssignToTeacher courseassign)
        {
            if (ModelState.IsValid)
            {
                db.CourseAssignToTeachers.Add(courseassign);
                db.SaveChanges();
                ViewBag.Message = "Course Assigned Successful";

                //  return RedirectToAction("Index");
            }

            ViewBag.CourseID = new SelectList(db.Courses, "Id", "CourseCode", courseassign.CourseID);
            ViewBag.DepartmentId = new SelectList(db.Deparments, "Id", "DeptCode", courseassign.DepartmentId);
            ViewBag.TeacherId = new SelectList(db.Teachers, "Id", "Name", courseassign.TeacherId);
            return View(courseassign);
        }

        public JsonResult SaveCourseAssign(CourseAssignToTeacher courseAssign)
        {
            var checkAssignedCoueses =
                db.CourseAssignToTeachers.Where(m => m.CourseID == courseAssign.CourseID)
                    .ToList();

            if (checkAssignedCoueses.Count > 0)
                return Json(false);

            else
            {
                db.CourseAssignToTeachers.Add(courseAssign);
                db.SaveChanges();

                var teacher = db.Teachers.FirstOrDefault(m => m.Id == courseAssign.TeacherId);

                if (teacher != null)
                {
                    //teacher.CreditLeft = CourseAssignToTeacher.CreditLeft;
                    teacher.CreditLeft = courseAssign.CreditLeft;
                    db.Teachers.AddOrUpdate(teacher);
                    db.SaveChanges();

                    var course = db.Courses.FirstOrDefault(m => m.Id == courseAssign.CourseID);

                    if (course != null)
                    {
                        //course.CourseStatus = true;
                        course.CourseAssignTo = teacher.Name;
                        courseAssign.Name= course.Course_Name;
                        courseAssign.Credit = course.Course_Credit;
                        db.Courses.AddOrUpdate(course);
                        db.SaveChanges();

                        return Json(true);
                    }
                    else
                    {
                        return Json(false);
                    }
                }
                else
                {
                    return Json(false);
                }
            }
        }

        // GET: /CourseAssign/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseAssignToTeacher courseassign = db.CourseAssignToTeachers.Find(id);
            if (courseassign == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseID = new SelectList(db.Courses, "Id", "CourseCode", courseassign.CourseID);
            ViewBag.DepartmentId = new SelectList(db.Deparments, "Id", "DeptCode", courseassign.DepartmentId);
            ViewBag.TeacherId = new SelectList(db.Teachers, "Id", "Name", courseassign.TeacherId);
            return View(courseassign);
        }

        // POST: /CourseAssign/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DepartmentId,TeacherId,CreditTaken,CreditLeft,CourseID,Name,Credit")] CourseAssignToTeacher courseassign)
        {
            if (ModelState.IsValid)
            {
                db.Entry(courseassign).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseID = new SelectList(db.Courses, "Id", "CourseCode", courseassign.CourseID);
            ViewBag.DepartmentId = new SelectList(db.Deparments, "Id", "DeptCode", courseassign.DepartmentId);
            ViewBag.TeacherId = new SelectList(db.Teachers, "Id", "Name", courseassign.TeacherId);
            return View(courseassign);
        }

        // GET: /CourseAssign/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseAssignToTeacher courseassign = db.CourseAssignToTeachers.Find(id);
            if (courseassign == null)
            {
                return HttpNotFound();
            }
            return View(courseassign);
        }

        // POST: /CourseAssign/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CourseAssignToTeacher courseassign = db.CourseAssignToTeachers.Find(id);
            db.CourseAssignToTeachers.Remove(courseassign);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

University Management System/Views/CourseAssignToTeacher/Save.cshtml
@model University_Management_System.Models.CourseAssignToTeacher

@{
    ViewBag.Title = "Course Assign";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Course Assign to Teacher</h2>

@*<div align="center">
        @if (@ViewBag.Message != null)
        {
            <span class="alert alert-success">@ViewBag.Message</span>
        }
    </div>*@


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">

            <label class="control-label col-md-2">Department</label>

            <div class="col-md-10">

                <select name="departmentId" id="departmentId">

                    <option value="">Select Department</option>
                    @foreach (var aDepartment in ViewBag.Departments)
                    {
                        <option value="@aDepartment.Id">@aDepartment.DeptName</option>
                    }

                </select><label id="DeptErrorLabel" style="color: red;"></label>


            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherId, "Teacher", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                <select name="teacherId" id="teacherId"></select><label id="TeacherErrorLabel" style="color: red;"></label>


            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Credit to be taken</label>
            <div class="col-md-10">

                <input type="text" name="creditTaken" id="creditTaken" readonly="readonly" class="form-control" />

            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Remaining credit</label>
            <div class="col-md-10">


                <input type="text" name="creditLeft" id="creditLeft" readonly="readonly" class="form-control" />


            </div>
        </div>


        <div class="form-group">

            <label class="control-label col-md-2">Course Code</label>

            <div class="col-md-10">

                <select name="courseId" id="courseId"></select><label id="CourseErrorLabel" style="color: red;"></label>


            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">


                <input type="text" name="courseName" id="courseName" readonly="readonly" class="form-control" />


            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Credit, new { @class = "control-label col-md-2", @readonly = "readonly" })
            <div class="col-md-10">


                <input type="text" name="courseCredit" id="courseCredit" readonly="readonly" class="form-control" />


            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" name="submit" id="submit" value="Assign" class="btn btn-primary btn-sm" />
            </div>
        </div>

        <br /><br />

        <div class="form-group">
            <div class="col-md-10">
                <p>
                    <label id="AssignSuccessLabel" style="color: green;"></label>
                    <label id="AssignErrorLabel" style="color: red;"></label>
                </p>
            </div>
        </div>

    </div>
}

@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

@section Scripts {

<script src="~/Scripts/jquery-2.1.4.js"></script>
    <script>
        $(function () {

            $("#departmentId").change(function () {

                ResetLabel();

                $("#teacherId").empty();
                var departmentId = $("#departmentId").val();
                var jasonData = { deptId: departmentId };
                $("#teacherId").append('<option value=0>Select Teacher</option>');
                $.ajax({

                    type: "POST",
                    url: '@Url.Action("GetTeacherByDeptId", "CourseAssignToTeacher")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jasonData),
                    dataType: "json",
                    success: function(data) {
                        $.each(data, function(key, value) {

                            $("#teacherId").append('<option value=' + value.Id + '>' + value.Name + '</option>');

                        });
                    },

                });


                $("#courseId").empty();
                var jasonData = { deptId: departmentId };
                $("#courseId").append('<option value=0>Select Course</option>');
                $.ajax({

                    type: "POST",
                    url: '@Url.Action("GetCourseByDeptId", "CourseAssignToTeacher")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jasonData),
                    dataType: "json",
                    success: function (data) {
                        $.each(data, function (key, value) {

                            $("#courseId").append('<option value=' + value.Id + '>' + value.Course_Code + '</option>');

                        });
                    },

                });

                return false;
            });

            $("#teacherId").change(function () {

                var teacherSelected = $("#teacherId").val();
                var jsonData = { TeacherId: teacherSelected };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetTeacherById", "CourseAssignToTeacher")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jsonData),
                    dataType: "json",
                    success: function (data) {

                       // alert(data.CreditTaken + " " + data.CreditLeft);

                        $("#creditTaken").val(data.CreditTaken);
                        $("#creditLeft").val(data.CreditLeft);

                    },

                });

               
                    $("#creditTaken").val("");
                    $("#creditLeft").val("");
                
                return false;
            });

            $("#courseId").change(function () {

                DecisionLabel();

                var courseSelected = $("#courseId").val();
                var jsonData = { courseId: courseSelected };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCourseById", "CourseAssignToTeacher")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jsonData),
                    dataType: "json",
                    success: function (data) {

                        //alert(data.CourseName + " " + data.CourseCredit);

                        $("#courseName").val(data.Course_Name);
                        $("#courseCredit").val(data.Course_Credit);
                    },
                });
                
                    $("#courseName").val("");
                    $("#courseCredit").val("");
                
                return false;
            });


            $("#submit").click(function() {
                var errorValue = 0;
                // ResetLabel();
                var departmentId = $("#departmentId").val();

                if (departmentId == 0) {
                    $("#DeptErrorLabel").text("Select  Department ");
                    errorValue = 1;
                }

                var teacherId = $("#teacherId").val();

                if (teacherId == 0) {
                    $("#TeacherErrorLabel").text("Select Teacher ");
                    errorValue = 1;
                }

                var courseId = $("#courseId").val();
                if (courseId == 0) {
                    $("#CourseErrorLabel").text("Select  Course ");
                    errorValue = 1;
                }
                if (errorValue == 1) {
                    return false;
                }
                else {
                   // alert("Course Credit: " + $("#courseCredit").val());

                    var creditAvailable = $("#creditLeft").val() - $("#courseCredit").val();
                    var status = false;
                    if (creditAvailable < 0) {

                        status = confirm("This will cross total assigned credit for this teacher. Do You Proced...");
                    }
                    if (status == true || creditAvailable > 0) {

                        var totalTakenCredit = $("#creditTaken").val();

                        var jasonData = { DepartmentId: departmentId, TeacherId: teacherId, CourseId: courseId, CreditTaken: totalTakenCredit, CreditLeft: creditAvailable };
                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("SaveCourseAssign", "CourseAssignToTeacher")',
                            contentType: "application/json; charset=utf-8",
                            data: JSON.stringify(jasonData),
                            dataType: "json",
                            success: function(data) {

                                if (data == true)

                                    $("#AssignSuccessLabel").text("Successfully Assigned");
                                    //alert("Successfully Assigned");
                                else {
                                    $("#AssignErrorLabel").text("This course is already Assigned");
                                    //alert("This course is already Assigned");
                                }
                                ResetValue();
                            },
                        });

                    }
                    return false;
                }

            });
            return false;
        });

        function ResetValue() {
            $("#creditLeft").val("");
            $("#creditTaken").val("");
            $("#courseId").empty();
            $("#eacherId").empty();
            $("#courseName").val("");
            $("#courseCredit").val("");
            $("#departmentId").prop("selectedIndex", 0);
        }

        function ResetLabel() {
            $("#DeptErrorLabel").text("");
            $("#TeacherErrorLabel").text("");
            $("#CourseErrorLabel").text("");
        }

        function DecisionLabel() {
            $("#AssignSuccessLabel").text("");
            $("#AssignErrorLabel").text("");
        }

    </script>


}

University Management System/Views/CourseAssignToTeacher/ViewCourseStatistics.cshtml
@model University_Management_System.Models.CourseAssignToTeacher
    
@{
    ViewBag.Title = "ViewCourseStatistics";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>View Course Statistics</h2>*@

<fieldset>

    <legend>View Course Statistics</legend>

    @using (Html.BeginForm())
    {
        @Html.LabelFor(model => model.DepartmentId, "Department", new { @class = "control-label col-md-2" })

        <div class="col-md-10">

            <select name="departmentId" id="departmentId" class="form-control">

                <option value="">Select Department</option>

                @foreach (var aDepartment in ViewBag.Departments)
                {
                    <option value="@aDepartment.Id">@aDepartment.DeptName</option>
                }

            </select><label id="DeptErrorLabel" style="color: red;"></label>

        </div>

        <label id="messageLabel" style="color: #00B16A; font-weight: normal; font-size: 20px;"></label>

        <div id="htmlTableDiv">

        </div>
    }

</fieldset>

@section Scripts {
    <script src="~/Scripts/jquery-2.1.4.js"></script>
    <script>

        $(function () {

            $("#departmentId").change(function () {

                var departmentId = $("#departmentId").val();

                $("#messageLabel").text("");
                var jsonData = { deptId: departmentId };

                $.ajax({

                    type: "POST",
                    url: '@Url.Action("ShowCourseStatistics", "CourseAssignToTeacher")',
                   
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jsonData),
                    dataType: "json",
                    success:function(data) {

                        var table = $('<table id="statisticsTable" border="1" class="table" >');

                        table.append('<th style="text-align: center; border-right: 1px solid #ffffff;">Code</th>');
                        table.append('<th style="text-align: center; border-right: 1px solid #ffffff;">Title</th>');
                       table.append('<th style="text-align: center; border-right: 1px solid #ffffff;">Semester</th>');
                        table.append('<th style="text-align: center; border-right: 1px solid #ffffff;">Assigned To</th></table>');
                        table.css('background-color', '#22D7A0');

                        var tableRow = false;

                        $("#htmlTableDiv").show();

                        $.each(data, function(key, value) {

                            var trow = $('<tr>');
                            var assignedTo = value.CourseAssignTo;

                            if (assignedTo == null || assignedTo == "")
                                assignedTo = 'Not Assigned Yet';
                                
                            trow.append('<td style="text-align: center; border-right: 1px solid #ffffff;">' + value.Course_Code + '</td>');
                            trow.append('<td style="text-align: center; border-right: 1px solid #ffffff;">' + value.Course_Name + '</td>');
                            trow.append('<td style="text-align: center; border-right: 1px solid #ffffff;">' + value.Semester.Semester_Name+ '</td>');
                            trow.append('<td style="text-align: center; border-right: 1px solid #ffffff;">' + assignedTo + '</td></tr>');

                            table.append(trow);

                            tableRow = true;

                        });

                        $("tr:odd", table).css('background-color', '#F5F5F5');
                        $("tr:even", table).css('background-color', '#EEEEEE');


                        $("#htmlTableDiv").html(table);

                        if (tableRow == false)
                        {
                            $("#htmlTableDiv").hide();
                            if (departmentId != 0)
                                $("#messageLabel").text("This Department has no Course.");
                        }
                    }

                });

                return false;

            });

        });

    </script>
}